### ISSUE TITLE
Accents are not marshalled correctly

### ISSUE THREAD

**Issue by 03July** [ssuluh/osrmnet#34]
I found a bug in RouteResult.cpp (line 105) :
routeStep->Name = msclr::interop::marshal_as<System::String^>(name);
where the accents is not converted correctly.

For example : Got 'Rue Jacques DestrÃ©e' but expected 'Rue Jacques Destrée'. It seems OSRM lib is encoded with UTF-8.

I'm an experienced developer in C#, Java & Objective-C but I'm not familiar with C++/CLI so I cannot propose a fix.

Kind regards,
Daniel

**Comment by ssuluh** [comment]
Hi Daniel,
Just to help me out, do you still have the coordinate for the route and what region of pbf map you're using?

**Comment by 03July** [comment]
Hi Surya,

I'm using the region : https://download.geofabrik.de/europe/france-latest.osm.pbf but the sub-region 
: https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf should work.

The route is :
http://127.0.0.1:5000/route/v1/driving/2.349566,48.829717;2.472986,48.629575?steps=true

Note also that the lane node in this route will be cause another bug :
const auto& laneList = intersection.values.at("lanes").get<osrm::json::Array>().values;
for (const auto &lane : laneList)
{
result->Lanes->Add(msclr::interop::marshal_as<System::String^>(lane.get<osrm::json::String>().value));
}

Please find the modified project on Dropbox  : https://www.dropbox.com/s/94jyc6a1dlmvvps/OSRM.NET.zip?dl=0
I'm working on it to : 
- Fix the lane bug
- To upgrade to libosrm **5.12.0**
- Add support for NumberOfAlternatives
- Add support for AnnotationsType
- Add support for GeometriesType.GeoJSON

The modified project seems to work correctly with libosrm **5.12.0**.

Kind regards,
Daniel

**Comment by ssuluh** [comment]
Hi Daniel, thanks for the heads up and I'll definitely will look into your solution. I made progress last night.  It is caused by the libosrm compiled with non unicode. We still want to leave libosrm as is so the solution will have to be a string conversion. I tested it last night and it worked nicely, but I know I have to apply it everywhere that deals with string. 
On a different note, looking at the list that you're working on, I would be very grateful if you can contribute. We can separate the work by feature and by you forking the project and just issue pull request.  PM me if you're interested and we can work out the detail on how to best coordinate this.

PS: I think you can easily pick up c++/cli. What we're doing here is just to provide translation layer that I don't foresee it's going to be complicated.

**Comment by 03July** [comment]
Hi Surya,

Yes it would be nice to work together, how can I contact you directly so I can give my email to setup detail.

I already finish a full implementation of route in the modified project in Dropbox.
Indeed I feel comfortable to implement ProcessRouteLeg, ProcessManeuver ... as it is just to adapt the code as the syntax is already there.

**Comment by ssuluh** [comment]
Daniel, you can reach me at ssuluh@yahoo.com

**Comment by ssuluh** [comment]
Addressed with #36
