### ISSUE TITLE
System.BadImageFormatException : 未能加载文件或程序集“osrm.net, Version=1.0.0.26, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。试图加载格式不正确的程序。

### ISSUE THREAD

**Issue by xilutian** [ssuluh/osrmnet#65]
![image](https://user-images.githubusercontent.com/14370659/69229990-7489c100-0bc1-11ea-9f77-115a1e91b319.png)

why  can not load osrmnet.dll

**Comment by ssuluh** [comment]
It look like you're running it in 32 bit. OSRM.net can't run in 32 bit because the underlying osrm.lib is 64 bit. Make sure your test is set to run in x64 like below:
![image](https://user-images.githubusercontent.com/12562475/69299941-d8bb7d80-0bdf-11ea-9a78-fe32b05c96ee.png)

**Comment by xilutian** [comment]
Thank you. I'm a novice. I want to add a real-time train navigation. How to add a profile in this project

**Comment by ssuluh** [comment]
> Thank you. I'm a novice. I want to add a real-time train navigation. How to add a profile in this project
@xilutian, the best way is to start reading the docs of the Project-OSRM itself ((https://github.com/Project-OSRM/osrm-backend). I know profile based of LUA script, I'm not familiar with them (https://github.com/Project-OSRM/osrm-backend/tree/master/profiles). 

I'm going to close this issue since the op is resolved.
