### ISSUE TITLE
How to use instructions?

### ISSUE THREAD

**Issue by tekeroth-snapcode** [ssuluh/osrmnet#86]
Hello again,
I see no instructions on how to use the lib. I cannot build as per instructions (see here: https://github.com/osrmnet/osrmnet/issues/85), but I see that after cloning this repo, I see the  `osrm_5.26.0.zip` in `osrmnet\src\osrm.net\libosrm\redist`.

However, how am I supposed to use that? That ZIP-file contains exe files; is the idea to start a Process within the .NET application, run that application and communication somehow? Or what am I missing?

**Comment by tekeroth-snapcode** [comment]
Update: 

By following the instructions [here](https://github.com/Project-OSRM/osrm-backend#using-docker), the output is a bunch of osrm files. The problem is that using the docker image as above (latest) produces files using osrm version 0.5.27 but OsrmNet doe not support it, but instead requires 0.5.26 which is not readily available as a docker image (see [here](https://github.com/Project-OSRM/osrm-backend/issues/6231)).

However, after cloning the repo, there is a ZIP-file, mentioned above, that seems to contain the correct OSRM version for Windows. This can be executed the same way as the docker instructions (same flags args etc), and doing that will produce osrm files that can be used with osrmnet.

**Comment by ssuluh** [comment]
@tekeroth-snapcode.  The way the c++/cli binding works currently, it needs specific Windows build version of osrm library that contains the .lib files.  This project does not cover how to build osrm library for windows target specifically as windows platform is officially not supported by the parent project osrm.  The zip file that you observed being pulled is a snapshot of windows build for a given version of osrm, i have to do that since they're no longer provided windows build anymore.  Hope this answer your question.
